version: 2

models:
  - name: dim_time
    description: "Dimensión de tiempo con atributos de calendario y fiscal"
    columns:
      - name: date_sk
        description: "Surrogate key de la fecha en formato YYYYMMDD"
        tests: [unique, not_null]
      - name: date_value
        description: "Fecha real"
        tests: [unique, not_null]
      - name: year
        description: "Año calendario"
        tests: [not_null]
      - name: month
        description: "Mes calendario"
        tests: [not_null]
      - name: day
        description: "Día del mes"
        tests: [not_null]

  - name: dim_customer
    description: "Dimensión cliente (SCD2) con historial de cambios"
    columns:
      - name: customer_sk
        tests: [unique, not_null]
      - name: customer_id
        tests: [not_null]
      - name: nombre
      - name: apellido
      - name: email
        tests: [unique, not_null]
      - name: fecha_registro
      - name: segment_sk
        tests:
          - relationships:
              arguments:
                to: ref('dim_customer_segment')
                field: segment_sk
      - name: current_flag
        tests: [not_null]
      - name: eff_from
      - name: eff_to
      - name: notes

  - name: dim_customer_segment
    description: "Mini-dimensión de segmentación de clientes"
    columns:
      - name: segment_sk
        tests: [unique, not_null]
      - name: segment_code
        tests: [not_null]
      - name: segment_name
      - name: loyalty_tier
      - name: risk_score
      - name: last_behavior_flag
      - name: description

  - name: dim_product
    description: "Dimensión producto (SCD2 parcial)"
    columns:
      - name: product_sk
        tests: [unique, not_null]
      - name: product_id
        tests: [not_null]
      - name: name
      - name: description
      - name: category_sk
        tests:
          - relationships:
              arguments:
                to: ref('dim_category')
                field: category_sk
      - name: active_flag
      - name: current_price
        tests: [not_null]
      - name: current_flag
        tests: [not_null]
      - name: eff_from
      - name: eff_to

  - name: dim_category
    description: "Dimensión categoría de productos"
    columns:
      - name: category_sk
        tests: [unique, not_null]
      - name: category_id
        tests: [not_null]
      - name: name

  - name: dim_address
    description: "Dimensión dirección de envío (SCD2)"
    columns:
      - name: address_sk
        tests: [unique, not_null]
      - name: address_id
        tests: [not_null]
      - name: usuario_id
        tests: [not_null]
      - name: calle
      - name: ciudad
      - name: provincia
      - name: pais
      - name: postal_code
      - name: current_flag
        tests: [not_null]
      - name: eff_from
      - name: eff_to

  - name: dim_payment_method
    description: "Dimensión método de pago (SCD1)"
    columns:
      - name: payment_method_sk
        tests: [unique, not_null]
      - name: payment_method_id
        tests: [not_null]
      - name: name
      - name: description

  - name: dim_order_status
    description: "Dimensión estado de orden (SCD1)"
    columns:
      - name: order_status_sk
        tests: [unique, not_null]
      - name: status_code
        tests: [not_null]
      - name: description

  - name: dim_review
    description: "Dimensión reseñas de productos"
    columns:
      - name: review_sk
        tests: [unique, not_null]
      - name: review_id
        tests: [not_null]
      - name: product_sk
        tests:
          - relationships:
              arguments:
                to: ref('dim_product')
                field: product_sk
      - name: customer_sk
        tests:
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_sk
      - name: rating
        tests: [not_null]
      - name: comment_length
      - name: review_date